name: upcrush
description: "UpCrush — O teu copiloto de conversa."
publish_to: 'none'

version: 1.0.0+15

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  http: ^1.2.0
  shared_preferences: ^2.5.5
  purchases_flutter: ^9.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/